### PR TITLE
chore(jqwik-micronaut): #8 Prepare for Release 1.0.

### PR DESCRIPTION
**Pull request by Nahuel92**
## Sonarqube scan results (default options)

sonarqube

## Dependencies check

dependencies

## Dev Notes

- Bumped up dependencies versions.
- Removed unnecessary ones.
- Bumped up Gradle version.
- Reformatted code.
- Removed unnecessary CLI file.

### CODE REVIEW

**Comment by jlink** [comment]
As for changing all single quotes to double quotes: They have slightly different semantics in Groovy. In most places using one or the other was a deliberate choice. Your changes probably won’t break the build but introduce unnecessary (IMO) difference to most other Gradle files within jqwik-team organisation.

**Review by jlink — COMMENTED** [review]
Apart from the quotes issue all looks fine.

**Comment by Nahuel92** [comment]
> As for changing all single quotes to double quotes: They have slightly different semantics in Groovy. In most places using one or the other was a deliberate choice. Your changes probably won’t break the build but introduce unnecessary (IMO) difference to most other Gradle files within jqwik-team organisation.

I wasn't aware of that, I just wanted to be more consistent with the use of quotes in that file.
I reverted those changes, please review it again to make sure the quotes style matches the one used in other Jqwik projects.

**Review by jlink — APPROVED** [review]
Thanks for the effort!

**Pull request merged**
